name: CI
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run the test suite
        run: cargo test

      - name: Build the Docker container
        run: docker build -t rust-log-analyzer .

      - name: Deploy to production
        uses: rust-lang/simpleinfra/github-actions/upload-docker-image@master
        with:
          image: rust-log-analyzer
          repository: rust-log-analyzer
          region: us-west-1
          redeploy_ecs_cluster: rust-ecs-prod
          redeploy_ecs_service: rust-log-analyzer
          aws_access_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        if: github.ref == 'refs/heads/master'
